# Generated by Django 4.2.3 on 2023-07-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the liquor brand.', max_length=50)),
                ('website', models.URLField(help_text="The URL of the brand's website.")),
                ('country', models.CharField(help_text='The country of origin of the company.', max_length=30)),
            ],
        ),
    ]
