# Generated by Django 4.2.3 on 2023-07-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bottle name', max_length=50)),
                ('numberOfBottles', models.IntegerField(help_text='Number on hand')),
                ('Brand', models.CharField(help_text='Enter the name of the liquor brand', max_length=50)),
            ],
        ),
    ]
