# Generated by Django 3.2.5 on 2023-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorList', '0003_rename_brand_liquor_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquor',
            name='description',
            field=models.TextField(blank=True, help_text='Enter an optional description of the liquor.'),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='numberOfBottles',
            field=models.IntegerField(),
        ),
    ]
