# Generated by Django 3.2.5 on 2023-08-16 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorList', '0006_alter_liquor_numberofbottles'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='founded',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
