# Generated by Django 3.2.5 on 2023-08-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquorList', '0007_brand_founded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorList.brand'),
        ),
    ]
